name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: chatman-media
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Bangkok
          committer_message: "chore: update metrics"

          plugin_introduction: yes  # общая информация о аккаунте

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors
          plugin_wakatime_limit: 5

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes  # отображение применяемых языков программирования
          plugin_languages_details: bytes-size, percentage  # дополнительная информация о коде размер и процент

          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic

          plugin_achievements: yes
          plugin_achievements_threshold: X  # (покажет фишки достижений которые еще не разблокированы)
          plugin_achievements_display: detailed  # детальное описание фишек достижений

          plugin_habits: yes  # активность за сутки и неделю
          plugin_habits_facts: yes  # отображает анализ вашей активность за неделю
          plugin_habits_charts: yes  # отображает характеристики

          plugin_licenses: yes  # информация о лицензиях
          plugin_licenses_setup: npm ci  # подробная информация о применяемых лицензиях

          plugin_support: yes  # плагин поддержки

          plugin_topics: yes  # плагин ипсользуемых тем
          plugin_topics_limit: 0
          plugin_topics_mode: icons