name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: chatman-media
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#8B5CF6&color_dots=#B0E0E6,#87CEEB,#4682B4,#1E90FF,#0069FF
            dist/github-contribution-grid-snake-dark.svg?color_snake=#8B5CF6&color_dots=#B0E0E6,#87CEEB,#4682B4,#1E90FF,#0069FF&palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}